# Generated by Django 5.2.15 on 2026-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='grading',
            field=models.CharField(choices=[('ungraded', 'Ungraded'), ('psa', 'PSA'), ('bgs', 'BGS'), ('sgc', 'SGC'), ('cgc', 'CGC'), ('other', 'Other')], default='ungraded', max_length=20),
        ),
    ]
