# Generated by Django 5.2.15 on 2026-08-26 20:18

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections', '0001_initial'),
        ('listings', '0004_remove_listing_condition_listing_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='accepting_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='accepting_trades',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='back_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/', validators=[apps.core.models.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='listing',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='collections.card'),
        ),
        migrations.AddField(
            model_name='listing',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='listings/', validators=[apps.core.models.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='listing',
            name='grading_company_other',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_serial_numbered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='serial_copy_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='serial_print_run',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['card'], name='listings_li_card_id_155b76_idx'),
        ),
    ]
