# Generated by Django 5.2.15 on 2026-08-26 20:18

import apps.core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0004_remove_listing_condition_listing_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='collections/sets/', validators=[apps.core.models.validate_image_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year', 'company__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='N/A', max_length=200)),
                ('team', models.CharField(blank=True, default='N/A', max_length=200)),
                ('card_number', models.CharField(max_length=30)),
                ('variation', models.CharField(blank=True, default='', max_length=200)),
                ('print_run', models.PositiveIntegerField(blank=True, null=True)),
                ('image_front', models.ImageField(blank=True, null=True, upload_to='collections/cards/', validators=[apps.core.models.validate_image_upload])),
                ('image_back', models.ImageField(blank=True, null=True, upload_to='collections/cards/', validators=[apps.core.models.validate_image_upload])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='collections.cardset')),
            ],
            options={
                'ordering': ['card_number', 'player_name'],
            },
        ),
        migrations.CreateModel(
            name='CardSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(default='N/A', max_length=200)),
                ('team', models.CharField(blank=True, default='N/A', max_length=200)),
                ('card_number', models.CharField(max_length=30)),
                ('variation', models.CharField(blank=True, default='', max_length=200)),
                ('print_run', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_submissions', to='listings.listing')),
                ('resulting_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='collections.card')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_submissions', to='collections.cardset')),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='cardset',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sets', to='collections.company'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['set', 'card_number'], name='collections_set_id_81dc22_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['player_name'], name='collections_player__b365f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='card',
            constraint=models.UniqueConstraint(fields=('set', 'card_number', 'variation', 'player_name'), name='unique_card_per_set_number_variation_player'),
        ),
        migrations.AddIndex(
            model_name='cardset',
            index=models.Index(fields=['category', 'year'], name='collections_categor_b5696d_idx'),
        ),
        migrations.AddIndex(
            model_name='cardset',
            index=models.Index(fields=['category', 'year', 'company'], name='collections_categor_008c18_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardset',
            constraint=models.UniqueConstraint(fields=('category', 'year', 'company', 'name'), name='unique_set_per_category_year_company_name'),
        ),
    ]
