# Generated by Django 5.2.15 on 2026-07-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='banner_image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='x_url',
            field=models.URLField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='user',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
