# Generated by Django 5.2.15 on 2026-07-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_avatar_image_url_user_banner_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_theme',
            field=models.CharField(choices=[('blue', 'Blue'), ('crimson', 'Crimson'), ('teal', 'Teal'), ('orange', 'Orange'), ('charcoal', 'Charcoal')], default='blue', max_length=20),
        ),
    ]
