# Generated by Django 5.2.15 on 2026-07-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_profile_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='also_buying',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='collection_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='selling_since_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tagline',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
