# Generated by Django 5.2.15 on 2026-07-29 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_0006_user_also_buying_user_collection_size_and_more_0007_user_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNoteChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('user', 'User'), ('event', 'Event')], max_length=20)),
                ('target_id', models.PositiveIntegerField()),
                ('old_text', models.TextField(blank=True, default='')),
                ('new_text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_note_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-created_at'], name='users_admin_target__12823e_idx')],
            },
        ),
    ]
