# Generated by Django 5.2.15 on 2026-07-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_also_buying_user_collection_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vendor_tier',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('basic', 'Basic')], default='basic', max_length=20),
        ),
    ]
