# Generated by Django 5.2.15 on 2026-08-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_adminnotechange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('vendor', 'Vendor'), ('customer', 'Customer'), ('admin', 'Admin'), ('owner', 'Owner')], default='customer', max_length=20),
        ),
    ]
