# Generated by Django 5.2.15 on 2026-08-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_vendor_tier'),
        ('users', '0010_alter_user_role'),
    ]

    operations = [
    ]
