# Generated by Django 5.2.15 on 2026-07-13 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_seed_events'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_maps/'),
        ),
        migrations.AddField(
            model_name='event',
            name='map_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BoothAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=50)),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('unlinked_vendor_name', models.CharField(blank=True, max_length=200)),
                ('unlinked_vendor_category', models.CharField(blank=True, max_length=50)),
                ('unlinked_vendor_contact', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_assignments', to='events.event')),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'role': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['booth_number'],
                'constraints': [models.UniqueConstraint(fields=('event', 'booth_number'), name='unique_booth_number_per_event')],
            },
        ),
    ]
