# Generated by Django 5.2.15 on 2026-07-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_map_image_event_map_visible_boothassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='map_image_preset',
            field=models.CharField(blank=True, choices=[('single_hall', 'Single Open Hall'), ('center_aisle', 'Hall with Center Aisle'), ('l_shaped', 'L-Shaped Hall'), ('two_room', 'Two Connected Rooms')], max_length=30),
        ),
    ]
