# Generated by Django 5.2.15 on 2026-07-14 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_map_image_preset'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vintage', 'Vintage'), ('modern', 'Modern'), ('pokemon', 'Pokémon'), ('memorabilia', 'Memorabilia'), ('supplies', 'Supplies')], max_length=50)),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_sections', to='events.event')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
