# Generated by Django 5.2.15 on 2026-07-15 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_mapsection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('map_image', models.ImageField(blank=True, null=True, upload_to='venue_maps/')),
                ('map_image_preset', models.CharField(blank=True, choices=[('single_hall', 'Single Open Hall'), ('center_aisle', 'Hall with Center Aisle'), ('l_shaped', 'L-Shaped Hall'), ('two_room', 'Two Connected Rooms')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='loyalty_priority_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='map_visible_to_vendors',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Booth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booth_number', models.CharField(max_length=50)),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booths', to='events.venue')),
            ],
            options={
                'ordering': ['booth_number'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='map_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.CreateModel(
            name='VenueSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('vintage', 'Vintage'), ('modern', 'Modern'), ('pokemon', 'Pokémon'), ('memorabilia', 'Memorabilia'), ('supplies', 'Supplies')], max_length=50)),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='events.venue')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='BoothRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlinked_vendor_name', models.CharField(blank=True, max_length=200)),
                ('unlinked_vendor_category', models.CharField(blank=True, max_length=50)),
                ('unlinked_vendor_contact', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('loyalty_hold', 'Loyalty hold'), ('requested', 'Requested'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('released', 'Released')], default='requested', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='events.booth')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booth_registrations', to='events.event')),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'role': 'vendor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['loyalty_hold', 'requested', 'confirmed'])), fields=('event', 'booth'), name='unique_active_registration_per_booth_per_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='booth',
            constraint=models.UniqueConstraint(fields=('venue', 'booth_number'), name='unique_booth_number_per_venue'),
        ),
    ]
