# Generated by Django 5.2.15 on 2026-07-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_port_legacy_map_data_to_venues'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapsection',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='map_image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='map_image_preset',
        ),
        migrations.DeleteModel(
            name='BoothAssignment',
        ),
        migrations.DeleteModel(
            name='MapSection',
        ),
    ]
