# Generated by Django 5.2.15 on 2026-07-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_orphaned_state_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venuesection',
            name='category',
            field=models.CharField(max_length=50),
        ),
    ]
