# Generated by Django 5.2.15 on 2026-07-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_remove_seeded_example_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
