# Generated by Django 5.2.15 on 2026-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_venue_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
