# Generated by Django 5.2.15 on 2026-07-27 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_registration_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity_type', models.CharField(choices=[('ticketing', 'Ticketing'), ('seating', 'Seating'), ('food', 'Food'), ('bathroom', 'Bathroom'), ('merchandise', 'Merchandise'), ('custom', 'Custom')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('logo_image', models.ImageField(blank=True, null=True, upload_to='amenity_logos/')),
                ('position_x', models.DecimalField(decimal_places=2, max_digits=5)),
                ('position_y', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='events.venue')),
            ],
            options={
                'verbose_name_plural': 'venue amenities',
                'ordering': ['id'],
            },
        ),
    ]
