# Generated by Django 5.2.15 on 2026-07-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_venueamenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueamenity',
            name='amenity_type',
        ),
    ]
