# Generated by Django 5.2.15 on 2026-08-04 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_merge_0016_event_announcement_0017_remove_venueamenity_amenity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='estimated_attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='estimated_cards',
        ),
    ]
